### ISSUE TITLE
Error using the flags (in nfblab_muse.m -> nfblab_process.m)

### ISSUE THREAD

**Issue by gar1ma** [arnodelorme/neurofeedbacklab#5]
Hello! 

I am trying to use the neurofeedbacklab software with NeuroneBittium (I have configured the nfblab_muse file accordingly) and I am constantly running into certain errors that I was hoping to get your help on. So I am able to get a baseline file and the spectral density plot when all the flags (namely badchanflag, icaflag and asrflag) are set to false. But as soon as I set any one (or combination of two) of the flags as true, in any of the modes (baseline as well as trial), it throws different kinds of error in each case. Majority of these errors are being generated in the nfblab_process.m file. I have attached screenshots for your reference.

Your insight into this would be greatly appreciated!
Looking forward to hearing from you

Thanks & Regards,
Garima 

PFA the screenshot of these errors along with a label explaining when they happen. 
[Errors.pdf](https://github.com/arnodelorme/neurofeedbacklab/files/10848653/Errors.pdf)

**Comment by arnodelorme** [comment]
Can you check if it works with the latest code. I have implemented a fix 4137db5

**Comment by arnodelorme** [comment]
Please reopen the issue if it does not fix the problem.

**Comment by gar1ma** [comment]
Hi,

The errors persist even after implementing the latest code. The errors displayed are the same for asrflag and icaflag (in both the modes) and a bit different for badchanflag as presented in the file here

There is an additional error that keeps on occurring frequently:  instead of sending the theta values as feedback it keeps saying "streaming" as the currentMsg (and this goes on in an infinite loop (the while loop that's present) unless and until I manually stop it). 

PFA the file with all the screenshots for reference.

 [Errors (2).pdf](https://github.com/arnodelorme/neurofeedbacklab/files/10859605/Errors.2.pdf)

**Comment by gar1ma** [comment]
> Please reopen the issue if it does not fix the problem.

Hi,

The errors persist even after implementing the latest code. The errors displayed are the same for asrflag and icaflag (in both the modes) and a bit different for badchanflag as presented in the file here

There is an additional error that keeps on occurring frequently: instead of sending the theta values as feedback it keeps saying "streaming" as the currentMsg (and this goes on in an infinite loop (the while loop that's present) unless and until I manually stop it).

PFA the file with all the screenshots for reference.

[Errors (2).pdf](https://github.com/arnodelorme/neurofeedbacklab/files/10859605/Errors.2.pdf)

**Comment by gar1ma** [comment]
Hi,

The errors persist even after implementing the latest code. The errors displayed are the same for asrflag and icaflag (in both the modes) and a bit different for badchanflag as presented in the file here

There is an additional error that keeps on occurring frequently: instead of sending the theta values as feedback it keeps saying "streaming" as the currentMsg (and this goes on in an infinite loop (the while loop that's present) unless and until I manually stop it).

PFA the file with all the screenshots for reference.

[Errors (2).pdf](https://github.com/arnodelorme/neurofeedbacklab/files/10859605/Errors.2.pdf)

**Comment by gar1ma** [comment]
> Please reopen the issue if it does not fix the problem.

Hi,

The errors persist even after implementing the latest code. The errors displayed are the same for asrflag and icaflag (in both the modes) and a bit different for badchanflag as presented in the file here

There is an additional issue that keeps on occurring frequently: instead of sending the theta values as feedback it keeps saying "streaming" as the currentMsg (and this goes on in an infinite loop (the while loop that's present) unless and until I manually stop it). I am unable to figure out as to why does this happen and how can it be resolved.

PFA the file with all the screenshots for reference.

[Errors (2).pdf](https://github.com/arnodelorme/neurofeedbacklab/files/10859605/Errors.2.pdf)

PS: Since I am not the owner/collaborator of the repo I am unable to reopen the issue. Can you please do it at your end?

**Comment by arnodelorme** [comment]
Would you mind streaming an existing file (see protocol [basic_offline](https://github.com/arnodelorme/neurofeedbacklab/tree/master/protocols/basic_offline)) and implementing the different options? Then could you send me what crashes?

For the asr_process error, it is likely because you are using an old version of the clean_rawdata plugin.

**Comment by gar1ma** [comment]
While running the offline protocol there is error only in the 'Trial mode + badchan flag true' case which is as follows:
_______________________________________________________________________

Starting new session...
Loading baseline ASR file data_nfblab_2023-03-02_11-18_asr_filter.mat...
eeg_checkset note: upper time limit (xmax) adjusted so (xmax-xmin)*srate+1 = number of frames
Removing 2 channel(s)...
eeg_checkset note: upper time limit (xmax) adjusted so (xmax-xmin)*srate+1 = number of frames
Interpolating missing channels...
Points (/32):Error using griddata
Unknown method.

Error in eeg_interp (line 245)
            [Xi,Yi,badchansdata(:,t)] = griddata(ygood, xgood , double(tmpdata(datachans,t)'),...

Error in nfblab_interp (line 12)
EEGOUT = eeg_interp(EEG, chanInds(:)', 'sphericalfast');

Error in nfblab_process (line 539)
                chunkFilt(nonEventChans,:) = nfblab_interp(chunkFilt(nonEventChans,:), g.input.chanlocs, g.preproc.badChans);

Error in run_offline (line 27)
nfblab_process(options{:});

**Comment by gar1ma** [comment]
Hello Arnaud!
This is a gentle reminder regarding this open issue.

**Comment by arnodelorme** [comment]
The second error is because of your version of MATLAB (too old). I have tried and it works for me.

For the MUSE, you cannot interpolate bad channels because there are too few channels. So you should not use the badchanflag option.

**Comment by arnodelorme** [comment]
Or it might be because of an old version of EEGLAB. Update EEGLAB.
